drop view DV_SH_VIEW;

create or replace view DV_SH_VIEW as select
P.PROD_NAME,
P.PROD_DESC,
P.PROD_CATEGORY,
P.PROD_SUBCATEGORY,
P.PROD_LIST_PRICE,
S.QUANTITY_SOLD,
S.AMOUNT_SOLD,
X.CUST_GENDER,
X.CUST_YEAR_OF_BIRTH,
X.CUST_MARITAL_STATUS,
X.CUST_INCOME_LEVEL,
R.COUNTRY_NAME,
R.COUNTRY_SUBREGION,
R.COUNTRY_REGION,
T.TIME_ID,
T.DAY_NAME,
T.CALENDAR_MONTH_NAME,
T.CALENDAR_YEAR from
SH.PRODUCTS P,
SH.SALES S,
SH.CUSTOMERS X,
SH.COUNTRIES R,
SH.TIMES T where
S.PROD_ID=P.PROD_ID and
S.CUST_ID=X.CUST_ID and
S.TIME_ID=T.TIME_ID and
X.COUNTRY_ID=R.COUNTRY_ID;